/**
 * ============================================================================
 * TASK DOMAIN ARCHITECTURE & INVARIANTS
 * ============================================================================
 *
 * Flow Hierarchy (Append-Only Downward Flow):
 *
 *   Task (Definition)
 *     ├── TaskAssignmentPolicy
 *     ├── SchedulePolicy
 *     └── LifecyclePolicy
 *       ↓
 *   TaskCycle (Expected Occurrence Instance)
 *       ↓
 *   ExecutionEvent (Physical Work Performed)
 *       ↓
 *   RewardTransaction (Economic Yield)
 *       ↓
 *   The Mark (Historical Ledger)
 *
 * Core Invariants:
 *
 * 1. IMMUTABLE UPSTREAM ARTIFACTS
 *    No downstream artifact may rewrite upstream definitions.
 *    TaskCycle cannot modify SchedulePolicy.
 *    ExecutionEvent cannot modify Task.
 *    RewardTransaction cannot modify TaskCycle.
 *
 * 2. SOLE PERFORMER REWARD
 *    The participant performing the physical work receives the Practice XP
 *    and Credits generated by that execution.
 *    A participant whose obligation is satisfied through cross-completion
 *    receives zero unperformed XP and zero unperformed Credits.
 *
 * 3. RECURRENCE IS AUTHORITATIVE
 *    SchedulePolicy defines expected recurrence.
 *    Discipline mechanics such as Precision and Order may interpret or
 *    expand execution windows but NEVER mutate target dates, cycle identities,
 *    or series anchors.
 *
 * 4. DEFERRAL INVARIANT
 *    A deferred cycle retains its original cycle_id and target_date.
 *    Deferral alters only the permitted execution window.
 *
 * 5. SUPERSEDED SEMANTICS
 *    A cycle may be marked 'superseded' when another valid real-world
 *    condition resolves the underlying need.
 *    The cycle closes without execution, XP, Credits, or participant penalty.
 *
 * 6. INTERNAL HISTORICAL ABSENCE
 *    'historical_absence' is an internal archival scheduling state.
 *    It is never a user-visible failure state or streak-breaker.
 *
 * 7. DERIVED DOMAIN
 *    Task domain is never stored on Task.
 *    It is derived exclusively from primary_discipline through
 *    DISCIPLINE_DOMAIN_MAP.
 *
 * 8. SECONDARY DISCIPLINES
 *    secondary_disciplines is always an array.
 *    Synthesis may therefore expand secondary yield from one discipline
 *    to N disciplines without changing the Task schema.
 *
 * 9. PERFORMANCE VS AUTHORIZATION
 *    Permission to perform a task does not determine reward attribution.
 *    Reward attribution is determined by completed_by_user_id.
 *
 * 10. STRICT REWARD IDEMPOTENCY
 *     A completed task cycle may produce exactly one RewardTransaction
 *     for a given performer.
 *
 * 11. NO PASSIVE REWARD ACCRUAL
 *     Schedule satisfaction, deferral, supersession, or cross-completion
 *     never generates Practice XP or Credits for a non-performer.
 * ============================================================================
 */

// ----------------------------------------------------------------------------
// DISCIPLINES & DOMAINS
// ----------------------------------------------------------------------------

export type TaskDomain =
  | 'kinetic'
  | 'erudite'
  | 'form'
  | 'keeping';

export type DisciplineTag =
  // Kinetic
  | 'motion'
  | 'force'
  | 'precision'

  // Erudite
  | 'reason'
  | 'inquiry'
  | 'synthesis'

  // Form
  | 'making'
  | 'craft'
  | 'composition'

  // Keeping
  | 'care'
  | 'order'
  | 'renewal';

/**
 * Single authoritative mapping from Discipline to Domain.
 *
 * Domain is derived and must not be persisted independently on Task.
 */
export const DISCIPLINE_DOMAIN_MAP: Record<DisciplineTag, TaskDomain> = {
  // Kinetic
  motion: 'kinetic',
  force: 'kinetic',
  precision: 'kinetic',

  // Erudite
  reason: 'erudite',
  inquiry: 'erudite',
  synthesis: 'erudite',

  // Form
  making: 'form',
  craft: 'form',
  composition: 'form',

  // Keeping
  care: 'keeping',
  order: 'keeping',
  renewal: 'keeping',
};

// ----------------------------------------------------------------------------
// TASK ORIGIN
// ----------------------------------------------------------------------------

export type TaskSourceType =
  | 'core'
  | 'ad_hoc'
  | 'encounter'
  | 'event';

// ----------------------------------------------------------------------------
// ASSIGNMENT & PERMISSION POLICIES
// ----------------------------------------------------------------------------

export type VisibilityScope =
  | 'private'
  | 'household'
  | 'designated';

export type AssignmentType =
  | 'pool'
  | 'individual';

/**
 * Defines who is permitted to physically perform a task.
 *
 * This does not determine reward attribution.
 * The performer is always resolved from ExecutionEvent.completed_by_user_id.
 */
export type PerformerScope =
  | 'owner'
  | 'assignee'
  | 'household'
  | 'designated';

export interface TaskAssignmentPolicy {
  /** User who owns/defines the task */
  owner_id: string;

  /** Who can see the task */
  visibility: VisibilityScope;

  /** Required when visibility === 'designated' */
  designated_user_ids?: string[];

  /** Whether responsibility belongs to a shared pool or individual */
  assignment_type: AssignmentType;

  /** Required when assignment_type === 'individual' */
  primary_assignee_id?: string;

  /** Who is permitted to perform the task */
  performer_scope: PerformerScope;

  /** Required when performer_scope === 'designated' */
  designated_performer_ids?: string[];
}

// ----------------------------------------------------------------------------
// RECURRENCE & SCHEDULING POLICIES
// ----------------------------------------------------------------------------

export type CadenceType =
  | 'one_off'
  | 'interval'
  | 'calendar_anchor';

export type DelayPolicy =
  | 'none'
  | 'bounded'
  | 'flexible';

export interface SchedulePolicy {
  cadence_type: CadenceType;

  /**
   * Interval cadence:
   * Number of days between scheduled cycle targets.
   */
  interval_days?: number;

  /**
   * Immutable YYYY-MM-DD origin for interval sequence calculation.
   *
   * seq_n target:
   * series_anchor_date + (n × interval_days)
   */
  series_anchor_date?: string;

  /**
   * Calendar recurrence anchor.
   *
   * week:
   *   value = ISO weekday 1–7
   *
   * month:
   *   value = day of month 1–31
   */
  calendar_anchor?: {
    unit: 'week' | 'month';
    value: number;
  };

  /**
   * Controls whether execution may occur outside the nominal target.
   */
  delay_policy: DelayPolicy;

  /**
   * Whether the task has an explicit time-of-day execution window.
   */
  has_strict_window: boolean;

  /** HH:mm, 24-hour local time */
  window_start_time?: string;

  /** HH:mm, 24-hour local time */
  window_end_time?: string;

  /** Maximum number of completed executions permitted per day */
  max_daily_completions?: number;

  /** Minimum time between executions */
  cooldown_hours?: number;
}

// ----------------------------------------------------------------------------
// LIFECYCLE & DISPOSITION
// ----------------------------------------------------------------------------

export type ExpirationAction =
  | 'archive'
  | 'expire_quietly';

export interface LifecyclePolicy {
  /**
   * Absolute expiration timestamp.
   * Primarily used for event-bound or explicitly expiring tasks.
   */
  expires_at?: string;

  /**
   * Disposition applied when expiration occurs.
   */
  on_expiration?: ExpirationAction;

  /**
   * Time-to-live for transient system encounters.
   */
  ttl_hours?: number;
}

/**
 * Runtime availability is separate from execution state.
 *
 * Expiration or archival never implies failure.
 */
export type LifecycleDisposition =
  | 'active'
  | 'archived'
  | 'expired_quietly';

// ----------------------------------------------------------------------------
// CORE TASK DEFINITION
// ----------------------------------------------------------------------------

export interface Task {
  task_id: string;

  title: string;
  description?: string;

  /**
   * Primary discipline interpretation of the task.
   *
   * Domain is derived through DISCIPLINE_DOMAIN_MAP.
   */
  primary_discipline: DisciplineTag;

  /**
   * Additional disciplines naturally developed by the task.
   *
   * Must not contain primary_discipline.
   */
  secondary_disciplines: DisciplineTag[];

  /**
   * Immutable task origin.
   */
  source_type: TaskSourceType;

  /**
   * External event reference when source_type === 'event'.
   */
  source_event_id?: string;

  /** Task creation metadata */
  created_at: string;
  created_by_user_id: string;

  /** Responsibility, visibility, and performance permissions */
  assignment: TaskAssignmentPolicy;

  /** Recurrence and execution timing */
  schedule: SchedulePolicy;

  /** Runtime availability and expiration */
  lifecycle: LifecyclePolicy;
}

// ----------------------------------------------------------------------------
// RUNTIME PARTICIPANT EXECUTION STATE
// ----------------------------------------------------------------------------

/**
 * Execution state remains deliberately binary with one explicit foothold
 * state for tasks that support a point of entry.
 *
 * No generic progress states are permitted.
 */
export type UserTaskState =
  | 'active'
  | 'foothold_established'
  | 'completed';

// ----------------------------------------------------------------------------
// TASK CYCLE
// ----------------------------------------------------------------------------

export type CycleStatus =
  | 'pending'
  | 'satisfied'
  | 'deferred'
  | 'historical_absence'
  | 'superseded';

export interface TaskCycle {
  /**
   * Deterministic identity for this recurrence occurrence.
   *
   * Examples:
   *   task_892:one_off
   *   task_892:int:seq_14
   *   task_104:cal:2026-W34-1
   */
  cycle_id: string;

  task_id: string;

  /**
   * Original scheduled target.
   *
   * Precision and Order may alter execution windows but never this date.
   */
  target_date: string;

  /** Resolved permitted execution window */
  window_start: string;
  window_end: string;

  /**
   * Records whether Precision altered the base execution window.
   */
  window_source:
    | 'base'
    | 'precision_elastic';

  /** Current resolution state of this occurrence */
  status: CycleStatus;

  /**
   * Operational responsibility resolved for this specific cycle.
   */
  responsible_user_id: string;

  satisfied_at?: string;
  satisfied_by_user_id?: string;
  resolved_at?: string;
}

// ----------------------------------------------------------------------------
// EXECUTION EVENT
// ----------------------------------------------------------------------------

/**
 * Immutable record that physical work was performed.
 *
 * This is deliberately separate from UserTaskState:
 * state describes runtime execution status,
 * while ExecutionEvent records the historical act of execution.
 */
export interface ExecutionEvent {
  completion_id: string;

  task_id: string;
  cycle_id: string;

  /**
   * Person who actually performed the work.
   *
   * This field is authoritative for Practice XP and Credit attribution.
   */
  completed_by_user_id: string;

  /**
   * Person responsible for the cycle at execution time.
   *
   * May differ from completed_by_user_id during cross-completion.
   */
  responsible_user_id: string;

  completed_at: string;

  /**
   * Immutable snapshot of task origin at execution time.
   */
  source_type: TaskSourceType;
}

// ----------------------------------------------------------------------------
// ECONOMIC YIELD
// ----------------------------------------------------------------------------

export interface RewardYield {
  /** XP awarded to the primary discipline */
  primary_discipline: DisciplineTag;
  primary_xp: number;

  /** XP awarded to naturally associated secondary disciplines */
  secondary_yields: Array<{
    discipline: DisciplineTag;
    xp: number;
  }>;

  /** Spendable Practice Credits earned by the performer */
  credits_earned: number;
}

// ----------------------------------------------------------------------------
// CARE RELIEF
// ----------------------------------------------------------------------------

/**
 * Conditional bonus generated by Care Mastery: Relief.
 *
 * This is separate from RewardYield because Care Relief is not inherent
 * to the underlying task's normal economic yield.
 */
export interface CareReliefAward {
  /** Additional Care XP awarded to the performer */
  care_xp: number;

  /** Additional Credits awarded to the performer */
  bonus_credits: number;

  /** Person whose immediate burden was relieved */
  relieved_user_id: string;
}

// ----------------------------------------------------------------------------
// REWARD TRANSACTION
// ----------------------------------------------------------------------------

/**
 * Immutable economic transaction produced by one execution.
 *
 * One execution cycle + performer may produce exactly one transaction.
 */
export interface RewardTransaction {
  /** UUID v4 */
  transaction_id: string;

  /**
   * Strict idempotency key:
   *
   * `${task_id}:${cycle_id}:${performer_user_id}`
   */
  idempotency_key: string;

  task_id: string;
  cycle_id: string;

  /**
   * Authoritative reward recipient.
   */
  performer_user_id: string;

  yield: RewardYield;

  /**
   * Present only when Care Relief validation succeeds.
   */
  care_relief?: CareReliefAward;

  processed_at: string;
}
